---
- name: Install nerd fonts via Homebrew Cask
  community.general.homebrew_cask:
    name: "{{ item.key }}"
    path: "/home/linuxbrew/.linuxbrew/bin"
    state: present
  loop: "{{ nerd_fonts | dict2items | selectattr('value', 'equalto', true) | list }}"
  loop_control:
    label: "{{ item.key }}"
  become: false
