---
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', '/home/' ~ ansible_ssh_user ~ '/.ssh/' ~ ansible_ssh_pub_key_file) }}"
    manage_dir: true
