---
base_packages:
  - ansible
  - apt-listchanges
  - apt-show-versions
  - apt-transport-https
  - apt-utils
  - apticron
  - bash-completion
  - bind9-host
  - bsdmainutils
  - bsdutils
  - ca-certificates
  - certbot
  - conntrack
  - coreutils
  - cpio
  - curl
  - debianutils
  - debsums
  - diffutils
  - dmidecode
  - dmsetup
  - dos2unix
  - ebtables
  - findutils
  - gdisk
  - git
  - gnupg
  - gpgv
  - grep
  - hostname
  - ipvsadm
  - jq
  - less
  - libtool
  - logrotate
  - lsb-base
  - mc
  - mergerfs
  - mutt
  - parted
  - pciutils
  - prometheus-node-exporter
  - python3-pip
  - restic
  - screen
  - socat
  - sudo
  - tar
  - tree
  - unhide
  - unzip
  - util-linux
  - uuid-runtime
  - vim
  - wget
  - xfsprogs
compress_packages:
  - bzip2
  - gzip
  - p7zip-full
  - xz-utils
  - zip
