---
- hosts: localhost
  name: Configure local system, basically testing playbook
  connection: local
  become: false
  tasks:
    - name: Configure sudo
      ansible.builtin.import_role:
        name: configure_sudo
      become: true
      tags:
        - sudo

    - name: Install linuxbrew
      ansible.builtin.import_role:
        name: install_linuxbrew
      tags:
        - brew

    - name: Setup apt repositories
      ansible.builtin.import_role:
        name: setup_apt_repos
      become: true
      tags:
        - apt-repos
        - docker

    - name: Setup security tools
      ansible.builtin.import_role:
        name: setup_security-tools
      tags:
        - security

    - name: Setup minimal packages
      ansible.builtin.import_role:
        name: setup_minimal
      become: true
      tags:
        - minimal

    - name: Setup network tools
      ansible.builtin.import_role:
        name: setup_network-tools
      become: true
      tags:
        - network

    - name: Setup Python uv packages
      ansible.builtin.import_role:
        name: setup_python-uv
      tags:
        - python
        - uv

    - name: Setup VS Code
      ansible.builtin.import_role:
        name: setup_vscode
      tags:
        - vscode

    - name: Setup IaC Terraform tooling
      ansible.builtin.import_role:
        name: setup_iac-terraform
      become: false
      tags:
        - iac
        - terraform

    - name: Setup extra IaC tooling
      ansible.builtin.import_role:
        name: setup_iac-extra
      become: false
      tags:
        - iac
        - iac-extra

    - name: Setup kube extra tooling
      ansible.builtin.import_role:
        name: setup_kube-extra
      tags:
        - kube
        - kubernetes

