---
- hosts: localhost
  name: Configure local system, basically testing playbook
  connection: local
  become: true
  tasks:
    - name: Configure sudo
      ansible.builtin.import_role:
        name: configure_sudo
      tags:
        - sudo

    - name: Install linuxbrew
      ansible.builtin.import_role:
        name: install_linuxbrew
      tags:
        - brew

    - name: Setup minimal packages
      ansible.builtin.import_role:
        name: setup_minimal
      tags:
        - minimal

    - name: Setup network tools
      ansible.builtin.import_role:
        name: setup_network-tools
      tags:
        - network

    - name: Report done
      ansible.builtin.import_role:
        name: report_done
      become: false
      tags:
        - always
