---
- hosts: kube
  become: false
  remote_user: "{{ ansible_ssh_user }}"
  tasks:
    - name: Setup Longhorn distributed storage
      ansible.builtin.import_role:
        name: setup_longhorn
      tags:
        - longhorn
        - storage

    - name: Setup kube-extra (kubeconfig + KUBECONFIG env)
      ansible.builtin.import_role:
        name: setup_kube-extra
      become: false
      tags:
        - kubeconfig
        - kubernetes

