---
- hosts: kube
  name: Upgrade Debian OS packages
  become: false
  remote_user: "{{ ansible_ssh_user }}"
  tasks:
    - name: Upgrade Debian packages
      ansible.builtin.import_role:
        name: debian_upgrade
      become: true
      tags:
        - upgrade

    - name: Upgrade Homebrew packages
      ansible.builtin.import_role:
        name: upgrade_brew
      become: false
      tags:
        - upgrade
        - brew

    # - name: Upgrade uv tools and packages
    #   ansible.builtin.import_role:
    #     name: upgrade_python-uv
    #   become: false
    #   tags:
    #     - upgrade
    #     - uv
